import type { Metadata } from "next";
import { Arima } from "next/font/google";
import { cn } from "./lib/utils";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from "@clerk/nextjs";
import PreLoader from "./components/PreLoader";
import { neobrutalism } from "@clerk/themes";

const arima = Arima({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: neobrutalism,
      }}
    >
      <html className="scroll-smooth" lang="en">
        <body
          className={cn(
            "flex min-h-screen flex-col bg-background text-foreground antialiased",
            arima.className
          )}
        >
          <ClerkLoading>
            <PreLoader />
          </ClerkLoading>
          <ClerkLoaded>
            <Header />
            <main className="relative mt-20 flex h-full flex-grow flex-col items-center">
              {children}
            </main>
            <Footer />
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
